### ISSUE TITLE
Where to download the VTTI-WZDB2020 dataset

### ISSUE THREAD

**Issue by alongqiyue** [VTTI/Segmentation-and-detection-of-work-zone-scenes#1]
hi, Where can I to download the VTTI-WZDB2020 dataset. thank you

**Comment by akashsonth** [comment]
We appreciate your interest in our project. The VTTI-WZDB2020 dataset is considered proprietary and, as a result, we are unable to release it to the public. However, we understand the value of the dataset and its potential for research purposes. Therefore, we have made available the weights for the models trained on this dataset. You can find and access these weights to aid in your own research. If you have any further questions or need assistance with the model weights, please let us know.

**Comment by JasonBourne1998** [comment]
> We appreciate your interest in our project. The VTTI-WZDB2020 dataset is considered proprietary and, as a result, we are unable to release it to the public. However, we understand the value of the dataset and its potential for research purposes. Therefore, we have made available the weights for the models trained on this dataset. You can find and access these weights to aid in your own research. If you have any further questions or need assistance with the model weights, please let us know.

@akashsonth Hi，thanks for the great work. May I ask is there a pre-trained model fitted for Model 1: Work Zone Object Segmentation with UNet and Model 2: Work Zone Object Segmentation With UNet Using Image Patches?
